plt.figure(0)
    plt.imshow(corr, cmap='gray')
    plt.title('Normalized Correlation Response Map')
    plt.colorbar()
    plt.scatter(*max_loc, c='r')
    max_loc_0 = rotate_point(max_loc, (fw/2, fh/2), -angle)
    plt.scatter(*max_loc_0, c='b')
    plt.show()